INSERT INTO CAR (MAKE, MODEL, VERSION, DOORS, GROSS_PRICE, NETT_PRICE, HP)
values ('MAKE', 'MODEL', 'VERSION', 'DOORS', 'GROSS_PRICE', 'NETT_PRICE', 'HP');


INSERT INTO car (MAKE, MODEL, VERSION, DOORS, GROSS_PRICE, NETT_PRICE, HP)
select MAKE, MODEL, VERSION, DOORS, GROSS_PRICE, NETT_PRICE, HP from CSVREAD('classpath:database_testdata.csv', null, 'fieldSeparator=;');

